/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin.dashboard.index'
import { Route as AdminDashboardThemesRouteImport } from './routes/admin.dashboard.themes'
import { Route as AdminDashboardStylesRouteImport } from './routes/admin.dashboard.styles'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin.dashboard.settings'
import { Route as AdminDashboardMenuRouteImport } from './routes/admin.dashboard.menu'
import { Route as AdminDashboardGalleryRouteImport } from './routes/admin.dashboard.gallery'
import { Route as AdminDashboardCategoriesRouteImport } from './routes/admin.dashboard.categories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardThemesRoute = AdminDashboardThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardStylesRoute = AdminDashboardStylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardMenuRoute = AdminDashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardGalleryRoute = AdminDashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardCategoriesRoute =
  AdminDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin/dashboard/gallery': typeof AdminDashboardGalleryRoute
  '/admin/dashboard/menu': typeof AdminDashboardMenuRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/styles': typeof AdminDashboardStylesRoute
  '/admin/dashboard/themes': typeof AdminDashboardThemesRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin/dashboard/gallery': typeof AdminDashboardGalleryRoute
  '/admin/dashboard/menu': typeof AdminDashboardMenuRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/styles': typeof AdminDashboardStylesRoute
  '/admin/dashboard/themes': typeof AdminDashboardThemesRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/categories': typeof AdminDashboardCategoriesRoute
  '/admin/dashboard/gallery': typeof AdminDashboardGalleryRoute
  '/admin/dashboard/menu': typeof AdminDashboardMenuRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/styles': typeof AdminDashboardStylesRoute
  '/admin/dashboard/themes': typeof AdminDashboardThemesRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/gallery'
    | '/admin/dashboard/menu'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/styles'
    | '/admin/dashboard/themes'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/gallery'
    | '/admin/dashboard/menu'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/styles'
    | '/admin/dashboard/themes'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/'
    | '/admin/dashboard/categories'
    | '/admin/dashboard/gallery'
    | '/admin/dashboard/menu'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/styles'
    | '/admin/dashboard/themes'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/themes': {
      id: '/admin/dashboard/themes'
      path: '/themes'
      fullPath: '/admin/dashboard/themes'
      preLoaderRoute: typeof AdminDashboardThemesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/styles': {
      id: '/admin/dashboard/styles'
      path: '/styles'
      fullPath: '/admin/dashboard/styles'
      preLoaderRoute: typeof AdminDashboardStylesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/menu': {
      id: '/admin/dashboard/menu'
      path: '/menu'
      fullPath: '/admin/dashboard/menu'
      preLoaderRoute: typeof AdminDashboardMenuRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/gallery': {
      id: '/admin/dashboard/gallery'
      path: '/gallery'
      fullPath: '/admin/dashboard/gallery'
      preLoaderRoute: typeof AdminDashboardGalleryRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/categories': {
      id: '/admin/dashboard/categories'
      path: '/categories'
      fullPath: '/admin/dashboard/categories'
      preLoaderRoute: typeof AdminDashboardCategoriesRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardCategoriesRoute: typeof AdminDashboardCategoriesRoute
  AdminDashboardGalleryRoute: typeof AdminDashboardGalleryRoute
  AdminDashboardMenuRoute: typeof AdminDashboardMenuRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardStylesRoute: typeof AdminDashboardStylesRoute
  AdminDashboardThemesRoute: typeof AdminDashboardThemesRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardCategoriesRoute: AdminDashboardCategoriesRoute,
  AdminDashboardGalleryRoute: AdminDashboardGalleryRoute,
  AdminDashboardMenuRoute: AdminDashboardMenuRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardStylesRoute: AdminDashboardStylesRoute,
  AdminDashboardThemesRoute: AdminDashboardThemesRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
